INFO2023-01-06 18:09:45,939 autoreload 15792  13456 Watching for file changes with StatReloader
INFO2023-01-06 18:09:52,581 basehttp 15792  17164 "GET /index/ HTTP/1.1" 200 20
INFO2023-01-06 18:11:40,450 autoreload 15792  13456 C:\Users\Admin\Desktop\django_project\test_project\students\views.py changed, reloading.
INFO2023-01-06 18:11:41,477 autoreload 1304  10576 Watching for file changes with StatReloader
ERROR2023-01-06 18:14:27,377 log 1304  3688 Internal Server Error: /index/
Traceback (most recent call last):
  File "C:\Users\Admin\Desktop\django_project\env\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\Admin\Desktop\django_project\env\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Admin\Desktop\django_project\env\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Admin\Desktop\django_project\env\lib\site-packages\django\views\generic\base.py", line 101, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\Admin\Desktop\django_project\test_project\students\views.py", line 18, in get
    return HttpResponse(val, status=200)
NameError: name 'val' is not defined
ERROR2023-01-06 18:14:27,386 basehttp 1304  3688 "GET /index/ HTTP/1.1" 500 72174
INFO2023-01-06 18:15:50,720 autoreload 1304  10576 C:\Users\Admin\Desktop\django_project\test_project\students\views.py changed, reloading.
INFO2023-01-06 18:15:51,834 autoreload 16132  9800 Watching for file changes with StatReloader
INFO2023-01-06 18:16:01,677 basehttp 16132  12016 "GET /index/ HTTP/1.1" 200 8
INFO2023-01-06 18:16:40,366 basehttp 16132  12016 "GET /index/ HTTP/1.1" 200 8
INFO2023-01-06 18:18:29,260 autoreload 16132  9800 C:\Users\Admin\Desktop\django_project\test_project\students\views.py changed, reloading.
INFO2023-01-06 18:18:30,268 autoreload 16648  9504 Watching for file changes with StatReloader
INFO2023-01-06 18:18:35,496 basehttp 16648  16340 "GET /index/ HTTP/1.1" 200 8
INFO2023-01-09 10:22:39,606 autoreload 16648  9504 C:\Users\Admin\Desktop\django_project\test_project\students\views.py changed, reloading.
INFO2023-01-09 10:22:40,734 autoreload 4360  10724 Watching for file changes with StatReloader
INFO2023-01-09 16:42:38,102 autoreload 4360  10724 C:\Users\Admin\Desktop\django_project\test_project\test_project\settings.py changed, reloading.
INFO2023-01-09 16:44:28,147 autoreload 1056  16360 Watching for file changes with StatReloader
INFO2023-01-09 16:49:17,755 autoreload 1056  16360 C:\Users\Admin\Desktop\django_project\test_project\test_project\settings.py changed, reloading.
INFO2023-01-09 16:49:18,797 autoreload 8924  14612 Watching for file changes with StatReloader
INFO2023-01-09 16:51:48,780 autoreload 8924  14612 C:\Users\Admin\Desktop\django_project\test_project\test_project\settings.py changed, reloading.
INFO2023-01-09 16:53:45,736 autoreload 13172  13428 Watching for file changes with StatReloader
INFO2023-01-09 16:54:13,936 autoreload 13172  13428 C:\Users\Admin\Desktop\django_project\test_project\test_project\settings.py changed, reloading.
INFO2023-01-09 16:54:14,952 autoreload 10384  15028 Watching for file changes with StatReloader
INFO2023-01-09 16:59:39,135 autoreload 10384  15028 C:\Users\Admin\Desktop\django_project\test_project\students\views.py changed, reloading.
INFO2023-01-09 16:59:40,218 autoreload 14824  3572 Watching for file changes with StatReloader
INFO2023-01-09 17:00:00,755 basehttp 14824  6360 "GET /index/ HTTP/1.1" 200 8
INFO2023-01-09 17:00:09,429 basehttp 14824  6360 "GET /index/ HTTP/1.1" 200 8
WARNING2023-01-09 17:00:33,570 log 14824  6360 Not Found: /index/logs
WARNING2023-01-09 17:00:33,571 basehttp 14824  6360 "GET /index/logs HTTP/1.1" 404 4100
INFO2023-01-09 17:01:24,978 autoreload 14824  3572 C:\Users\Admin\Desktop\django_project\test_project\students\views.py changed, reloading.
INFO2023-01-09 17:01:26,297 autoreload 11192  7280 Watching for file changes with StatReloader
INFO2023-01-09 17:03:23,841 autoreload 11192  7280 C:\Users\Admin\Desktop\django_project\test_project\students\views.py changed, reloading.
INFO2023-01-09 17:03:25,073 autoreload 5880  17032 Watching for file changes with StatReloader
INFO2023-01-09 17:03:32,884 autoreload 5880  17032 C:\Users\Admin\Desktop\django_project\test_project\students\views.py changed, reloading.
INFO2023-01-09 17:03:34,188 autoreload 2732  6872 Watching for file changes with StatReloader
INFO2023-01-09 18:08:54,210 autoreload 2732  6872 C:\Users\Admin\Desktop\django_project\test_project\students\views.py changed, reloading.
INFO2023-01-09 18:08:55,651 autoreload 10532  14388 Watching for file changes with StatReloader
INFO2023-01-09 18:09:09,608 autoreload 10532  14388 C:\Users\Admin\Desktop\django_project\test_project\students\views.py changed, reloading.
INFO2023-01-09 18:09:11,479 autoreload 1232  11136 Watching for file changes with StatReloader
INFO2023-01-09 18:09:36,214 autoreload 1232  11136 C:\Users\Admin\Desktop\django_project\test_project\students\views.py changed, reloading.
INFO2023-01-09 18:09:37,875 autoreload 16844  13452 Watching for file changes with StatReloader
INFO2023-01-09 18:11:30,827 autoreload 16844  13452 C:\Users\Admin\Desktop\django_project\test_project\students\views.py changed, reloading.
INFO2023-01-09 18:11:32,201 autoreload 11864  4828 Watching for file changes with StatReloader
INFO2023-01-09 18:11:41,942 autoreload 11864  4828 C:\Users\Admin\Desktop\django_project\test_project\students\views.py changed, reloading.
INFO2023-01-09 18:11:43,562 autoreload 12340  17224 Watching for file changes with StatReloader
INFO2023-01-09 18:12:26,240 autoreload 12340  17224 C:\Users\Admin\Desktop\django_project\test_project\students\views.py changed, reloading.
INFO2023-01-09 18:12:27,324 autoreload 15872  15444 Watching for file changes with StatReloader
INFO2023-01-09 18:25:36,082 autoreload 15872  15444 C:\Users\Admin\Desktop\django_project\test_project\students\views.py changed, reloading.
INFO2023-01-09 18:25:37,019 autoreload 4064  2384 Watching for file changes with StatReloader
INFO2023-01-09 18:26:19,159 autoreload 4064  2384 C:\Users\Admin\Desktop\django_project\test_project\students\urls.py changed, reloading.
INFO2023-01-09 18:26:20,085 autoreload 13784  9332 Watching for file changes with StatReloader
INFO2023-01-09 18:26:46,205 autoreload 13784  9332 C:\Users\Admin\Desktop\django_project\test_project\students\urls.py changed, reloading.
INFO2023-01-09 18:26:47,578 autoreload 10532  2188 Watching for file changes with StatReloader
INFO2023-01-09 18:26:53,926 basehttp 10532  8708 "GET /index/ HTTP/1.1" 200 8
ERROR2023-01-09 18:27:02,306 log 10532  8708 Internal Server Error: /logs/
Traceback (most recent call last):
  File "C:\Users\Admin\Desktop\django_project\env\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\Admin\Desktop\django_project\env\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Admin\Desktop\django_project\env\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Admin\Desktop\django_project\env\lib\site-packages\django\views\generic\base.py", line 101, in dispatch
    return handler(request, *args, **kwargs)
TypeError: Logs.get() takes 1 positional argument but 2 were given
ERROR2023-01-09 18:27:02,307 basehttp 10532  8708 "GET /logs/ HTTP/1.1" 500 68646
INFO2023-01-09 18:27:40,058 autoreload 10532  2188 C:\Users\Admin\Desktop\django_project\test_project\students\views.py changed, reloading.
INFO2023-01-09 18:27:41,067 autoreload 17212  1344 Watching for file changes with StatReloader
ERROR2023-01-09 18:27:45,372 log 17212  13708 Internal Server Error: /logs/
Traceback (most recent call last):
  File "C:\Users\Admin\Desktop\django_project\env\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\Admin\Desktop\django_project\env\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Admin\Desktop\django_project\env\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Admin\Desktop\django_project\env\lib\site-packages\django\views\generic\base.py", line 101, in dispatch
    return handler(request, *args, **kwargs)
TypeError: Logs.get() takes 0 positional arguments but 2 were given
ERROR2023-01-09 18:27:45,373 basehttp 17212  13708 "GET /logs/ HTTP/1.1" 500 68787
INFO2023-01-09 18:27:54,945 autoreload 17212  1344 C:\Users\Admin\Desktop\django_project\test_project\students\views.py changed, reloading.
INFO2023-01-09 18:27:55,885 autoreload 13928  16968 Watching for file changes with StatReloader
ERROR2023-01-09 18:29:15,374 log 13928  6468 Internal Server Error: /logs/
Traceback (most recent call last):
  File "C:\Users\Admin\Desktop\django_project\env\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\Admin\Desktop\django_project\env\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Admin\Desktop\django_project\env\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Admin\Desktop\django_project\env\lib\site-packages\django\views\generic\base.py", line 101, in dispatch
    return handler(request, *args, **kwargs)
TypeError: Logs.get() takes 1 positional argument but 2 were given
ERROR2023-01-09 18:29:15,376 basehttp 13928  6468 "GET /logs/ HTTP/1.1" 500 68783
INFO2023-01-09 18:36:09,800 autoreload 13928  16968 C:\Users\Admin\Desktop\django_project\test_project\students\views.py changed, reloading.
INFO2023-01-09 18:36:10,845 autoreload 6124  15008 Watching for file changes with StatReloader
INFO2023-01-09 18:36:12,527 autoreload 6124  15008 C:\Users\Admin\Desktop\django_project\test_project\students\views.py changed, reloading.
INFO2023-01-09 18:36:13,651 autoreload 16396  16636 Watching for file changes with StatReloader
ERROR2023-01-09 18:36:18,163 log 16396  15516 Internal Server Error: /logs/
Traceback (most recent call last):
  File "C:\Users\Admin\Desktop\django_project\env\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\Admin\Desktop\django_project\env\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Admin\Desktop\django_project\env\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Admin\Desktop\django_project\env\lib\site-packages\django\views\generic\base.py", line 101, in dispatch
    return handler(request, *args, **kwargs)
TypeError: Logs.get() takes 1 positional argument but 2 were given
ERROR2023-01-09 18:36:18,164 basehttp 16396  15516 "GET /logs/ HTTP/1.1" 500 68783
INFO2023-01-09 18:37:18,721 autoreload 16396  16636 C:\Users\Admin\Desktop\django_project\test_project\students\views.py changed, reloading.
INFO2023-01-09 18:37:19,683 autoreload 12084  16776 Watching for file changes with StatReloader
INFO2023-01-09 18:37:25,590 autoreload 12084  16776 C:\Users\Admin\Desktop\django_project\test_project\students\views.py changed, reloading.
INFO2023-01-09 18:37:26,501 autoreload 14036  16912 Watching for file changes with StatReloader
INFO2023-01-09 18:37:30,250 autoreload 14036  16912 C:\Users\Admin\Desktop\django_project\test_project\students\views.py changed, reloading.
INFO2023-01-09 18:37:31,256 autoreload 5236  11720 Watching for file changes with StatReloader
ERROR2023-01-09 18:37:32,929 log 5236  17208 Internal Server Error: /logs/
Traceback (most recent call last):
  File "C:\Users\Admin\Desktop\django_project\env\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\Admin\Desktop\django_project\env\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Admin\Desktop\django_project\env\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Admin\Desktop\django_project\env\lib\site-packages\django\views\generic\base.py", line 101, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\Admin\Desktop\django_project\test_project\students\views.py", line 30, in get
    return render(request, "students/logs.html",context= { })
  File "C:\Users\Admin\Desktop\django_project\env\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "C:\Users\Admin\Desktop\django_project\env\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\Admin\Desktop\django_project\env\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "C:\Users\Admin\Desktop\django_project\env\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "C:\Users\Admin\Desktop\django_project\env\lib\site-packages\django\template\engine.py", line 163, in get_template
    template, origin = self.find_template(template_name)
  File "C:\Users\Admin\Desktop\django_project\env\lib\site-packages\django\template\engine.py", line 145, in find_template
    template = loader.get_template(name, skip=skip)
  File "C:\Users\Admin\Desktop\django_project\env\lib\site-packages\django\template\loaders\base.py", line 29, in get_template
    return Template(
  File "C:\Users\Admin\Desktop\django_project\env\lib\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "C:\Users\Admin\Desktop\django_project\env\lib\site-packages\django\template\base.py", line 199, in compile_nodelist
    return parser.parse()
  File "C:\Users\Admin\Desktop\django_project\env\lib\site-packages\django\template\base.py", line 508, in parse
    raise self.error(token, e)
  File "C:\Users\Admin\Desktop\django_project\env\lib\site-packages\django\template\base.py", line 506, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\Admin\Desktop\django_project\env\lib\site-packages\django\template\defaulttags.py", line 810, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "C:\Users\Admin\Desktop\django_project\env\lib\site-packages\django\template\base.py", line 508, in parse
    raise self.error(token, e)
  File "C:\Users\Admin\Desktop\django_project\env\lib\site-packages\django\template\base.py", line 506, in parse
    compiled_result = compile_func(self, token)
  File "C:\Users\Admin\Desktop\django_project\env\lib\site-packages\django\template\defaulttags.py", line 905, in do_if
    nodelist = parser.parse(('elif', 'else', 'endif'))
  File "C:\Users\Admin\Desktop\django_project\env\lib\site-packages\django\template\base.py", line 513, in parse
    self.unclosed_block_tag(parse_until)
  File "C:\Users\Admin\Desktop\django_project\env\lib\site-packages\django\template\base.py", line 574, in unclosed_block_tag
    raise self.error(token, msg)
django.template.exceptions.TemplateSyntaxError: Unclosed tag on line 8: 'if'. Looking for one of: elif, else, endif.
ERROR2023-01-09 18:37:32,935 basehttp 5236  17208 "GET /logs/ HTTP/1.1" 500 157684
INFO2023-01-09 18:38:08,482 basehttp 5236  17208 "GET /logs/ HTTP/1.1" 200 63
INFO2023-01-09 18:39:15,550 basehttp 5236  17208 "GET /logs/ HTTP/1.1" 200 63
INFO2023-01-09 18:39:57,607 autoreload 5236  11720 C:\Users\Admin\Desktop\django_project\test_project\students\views.py changed, reloading.
INFO2023-01-09 18:39:58,658 autoreload 11624  2916 Watching for file changes with StatReloader
INFO2023-01-09 18:40:10,221 autoreload 11624  2916 C:\Users\Admin\Desktop\django_project\test_project\students\views.py changed, reloading.
INFO2023-01-09 18:40:11,125 autoreload 15424  10460 Watching for file changes with StatReloader
INFO2023-01-09 18:40:28,715 autoreload 15424  10460 C:\Users\Admin\Desktop\django_project\test_project\students\views.py changed, reloading.
INFO2023-01-09 18:40:29,650 autoreload 5044  15788 Watching for file changes with StatReloader
ERROR2023-01-09 18:40:33,038 log 5044  13136 Internal Server Error: /logs/
Traceback (most recent call last):
  File "C:\Users\Admin\Desktop\django_project\env\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\Admin\Desktop\django_project\env\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Admin\Desktop\django_project\env\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Admin\Desktop\django_project\env\lib\site-packages\django\views\generic\base.py", line 101, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\Admin\Desktop\django_project\test_project\students\views.py", line 30, in get
    context = super().get_context_data(**kwargs)
AttributeError: 'super' object has no attribute 'get_context_data'
ERROR2023-01-09 18:40:33,040 basehttp 5044  13136 "GET /logs/ HTTP/1.1" 500 72924
INFO2023-01-09 18:41:12,061 autoreload 5044  15788 C:\Users\Admin\Desktop\django_project\test_project\students\views.py changed, reloading.
INFO2023-01-09 18:41:13,012 autoreload 12844  13868 Watching for file changes with StatReloader
ERROR2023-01-09 18:41:15,308 log 12844  16104 Internal Server Error: /logs/
Traceback (most recent call last):
  File "C:\Users\Admin\Desktop\django_project\env\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\Admin\Desktop\django_project\env\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Admin\Desktop\django_project\env\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Admin\Desktop\django_project\env\lib\site-packages\django\views\generic\base.py", line 101, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\Admin\Desktop\django_project\test_project\students\views.py", line 30, in get
    context = super().get_context_data(request)
AttributeError: 'super' object has no attribute 'get_context_data'
ERROR2023-01-09 18:41:15,310 basehttp 12844  16104 "GET /logs/ HTTP/1.1" 500 72922
INFO2023-01-09 18:41:26,665 autoreload 12844  13868 C:\Users\Admin\Desktop\django_project\test_project\students\views.py changed, reloading.
INFO2023-01-09 18:41:27,643 autoreload 17056  14988 Watching for file changes with StatReloader
INFO2023-01-09 18:41:51,639 autoreload 17056  14988 C:\Users\Admin\Desktop\django_project\test_project\students\views.py changed, reloading.
INFO2023-01-09 18:41:52,602 autoreload 16208  14752 Watching for file changes with StatReloader
ERROR2023-01-09 18:41:54,543 log 16208  15408 Internal Server Error: /logs/
Traceback (most recent call last):
  File "C:\Users\Admin\Desktop\django_project\env\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\Admin\Desktop\django_project\env\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Admin\Desktop\django_project\env\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Admin\Desktop\django_project\env\lib\site-packages\django\views\generic\base.py", line 101, in dispatch
    return handler(request, *args, **kwargs)
TypeError: Logs.get() takes 1 positional argument but 2 were given
ERROR2023-01-09 18:41:54,545 basehttp 16208  15408 "GET /logs/ HTTP/1.1" 500 68783
INFO2023-01-09 18:42:05,168 autoreload 16208  14752 C:\Users\Admin\Desktop\django_project\test_project\students\views.py changed, reloading.
INFO2023-01-09 18:42:06,121 autoreload 6152  8232 Watching for file changes with StatReloader
ERROR2023-01-09 18:42:08,239 log 6152  6804 Internal Server Error: /logs/
Traceback (most recent call last):
  File "C:\Users\Admin\Desktop\django_project\env\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\Admin\Desktop\django_project\env\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Admin\Desktop\django_project\env\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Admin\Desktop\django_project\env\lib\site-packages\django\views\generic\base.py", line 101, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\Admin\Desktop\django_project\test_project\students\views.py", line 30, in get
    context = super().get_context_data(**kwargs)
AttributeError: 'super' object has no attribute 'get_context_data'
ERROR2023-01-09 18:42:08,241 basehttp 6152  6804 "GET /logs/ HTTP/1.1" 500 73090
INFO2023-01-10 11:50:43,773 autoreload 6152  8232 C:\Users\Admin\Desktop\django_project\test_project\students\views.py changed, reloading.
INFO2023-01-10 11:50:45,277 autoreload 16196  3848 Watching for file changes with StatReloader
INFO2023-01-10 11:50:52,521 autoreload 16196  3848 C:\Users\Admin\Desktop\django_project\test_project\students\views.py changed, reloading.
INFO2023-01-10 11:50:53,812 autoreload 17128  7672 Watching for file changes with StatReloader
INFO2023-01-10 11:50:56,582 basehttp 17128  13868 "GET /logs/ HTTP/1.1" 200 63
INFO2023-01-10 11:51:25,371 basehttp 17128  13868 "GET /logs/ HTTP/1.1" 200 85
INFO2023-01-10 12:13:57,825 basehttp 17128  11216 "GET /logs/ HTTP/1.1" 200 85
INFO2023-01-10 12:14:13,678 autoreload 17128  7672 C:\Users\Admin\Desktop\django_project\test_project\students\views.py changed, reloading.
INFO2023-01-10 12:14:14,752 autoreload 11684  15120 Watching for file changes with StatReloader
ERROR2023-01-10 12:14:34,517 log 11684  15040 Internal Server Error: /logs/
Traceback (most recent call last):
  File "C:\Users\Admin\Desktop\django_project\env\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\Admin\Desktop\django_project\env\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Admin\Desktop\django_project\env\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Admin\Desktop\django_project\env\lib\site-packages\django\views\generic\base.py", line 101, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\Admin\Desktop\django_project\test_project\students\views.py", line 31, in get
    filepath = os.path.join(settings.BASE_DIR, "debug3.log")
NameError: name 'os' is not defined
ERROR2023-01-10 12:14:34,519 basehttp 11684  15040 "GET /logs/ HTTP/1.1" 500 72567
INFO2023-01-10 12:14:59,189 autoreload 11684  15120 C:\Users\Admin\Desktop\django_project\test_project\students\views.py changed, reloading.
INFO2023-01-10 12:15:00,387 autoreload 14828  16644 Watching for file changes with StatReloader
ERROR2023-01-10 12:15:02,279 log 14828  8524 Internal Server Error: /logs/
Traceback (most recent call last):
  File "C:\Users\Admin\Desktop\django_project\env\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\Admin\Desktop\django_project\env\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Admin\Desktop\django_project\env\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Admin\Desktop\django_project\env\lib\site-packages\django\views\generic\base.py", line 101, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\Admin\Desktop\django_project\test_project\students\views.py", line 32, in get
    filepath = os.path.join(settings.BASE_DIR, "debug3.log")
NameError: name 'settings' is not defined
ERROR2023-01-10 12:15:02,282 basehttp 14828  8524 "GET /logs/ HTTP/1.1" 500 72591
INFO2023-01-10 12:17:44,602 autoreload 14828  16644 C:\Users\Admin\Desktop\django_project\test_project\students\views.py changed, reloading.
INFO2023-01-10 12:17:46,032 autoreload 14172  1580 Watching for file changes with StatReloader
ERROR2023-01-10 12:17:48,657 log 14172  7348 Internal Server Error: /logs/
Traceback (most recent call last):
  File "C:\Users\Admin\Desktop\django_project\env\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\Admin\Desktop\django_project\env\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Admin\Desktop\django_project\env\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Admin\Desktop\django_project\env\lib\site-packages\django\views\generic\base.py", line 101, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\Admin\Desktop\django_project\test_project\students\views.py", line 32, in get
    filepath = os.path.join(settings.BASE_DIR, "debug3.log")
NameError: name 'settings' is not defined
ERROR2023-01-10 12:17:48,661 basehttp 14172  7348 "GET /logs/ HTTP/1.1" 500 72591
INFO2023-01-10 12:18:05,808 autoreload 14172  1580 C:\Users\Admin\Desktop\django_project\test_project\students\views.py changed, reloading.
INFO2023-01-10 12:18:07,393 autoreload 14280  2444 Watching for file changes with StatReloader
ERROR2023-01-10 12:18:08,999 log 14280  13308 Internal Server Error: /logs/
Traceback (most recent call last):
  File "C:\Users\Admin\Desktop\django_project\env\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\Admin\Desktop\django_project\env\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Admin\Desktop\django_project\env\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Admin\Desktop\django_project\env\lib\site-packages\django\views\generic\base.py", line 101, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\Admin\Desktop\django_project\test_project\students\views.py", line 31, in get
    context = super().get_context_data(**kwargs)
AttributeError: 'super' object has no attribute 'get_context_data'
ERROR2023-01-10 12:18:09,003 basehttp 14280  13308 "GET /logs/ HTTP/1.1" 500 72924
INFO2023-01-10 12:19:57,391 autoreload 14280  2444 C:\Users\Admin\Desktop\django_project\test_project\students\views.py changed, reloading.
INFO2023-01-10 12:19:59,093 autoreload 12652  8404 Watching for file changes with StatReloader
INFO2023-01-10 12:20:24,427 autoreload 12652  8404 C:\Users\Admin\Desktop\django_project\test_project\students\views.py changed, reloading.
INFO2023-01-10 12:20:26,161 autoreload 10916  16064 Watching for file changes with StatReloader
INFO2023-01-10 12:20:51,491 autoreload 10916  16064 C:\Users\Admin\Desktop\django_project\test_project\students\views.py changed, reloading.
INFO2023-01-10 12:20:53,405 autoreload 10688  14892 Watching for file changes with StatReloader
INFO2023-01-10 12:21:25,220 autoreload 10688  14892 C:\Users\Admin\Desktop\django_project\test_project\students\views.py changed, reloading.
INFO2023-01-10 12:21:26,708 autoreload 13492  2832 Watching for file changes with StatReloader
INFO2023-01-10 12:21:52,283 autoreload 13492  2832 C:\Users\Admin\Desktop\django_project\test_project\students\views.py changed, reloading.
INFO2023-01-10 12:21:54,029 autoreload 8232  14312 Watching for file changes with StatReloader
ERROR2023-01-10 12:21:57,644 log 8232  864 Internal Server Error: /logs/
Traceback (most recent call last):
  File "C:\Users\Admin\Desktop\django_project\env\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\Admin\Desktop\django_project\env\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Admin\Desktop\django_project\env\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Admin\Desktop\django_project\env\lib\site-packages\django\views\generic\base.py", line 101, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\Admin\Desktop\django_project\test_project\students\views.py", line 31, in get
    f = open('/logs/debug3.logs', 'r')
FileNotFoundError: [Errno 2] No such file or directory: '/logs/debug3.logs'
ERROR2023-01-10 12:21:57,645 basehttp 8232  864 "GET /logs/ HTTP/1.1" 500 72634
INFO2023-01-10 12:22:17,909 autoreload 8232  14312 C:\Users\Admin\Desktop\django_project\test_project\students\views.py changed, reloading.
INFO2023-01-10 12:22:18,910 autoreload 12088  11092 Watching for file changes with StatReloader
ERROR2023-01-10 12:22:21,779 log 12088  14984 Internal Server Error: /logs/
Traceback (most recent call last):
  File "C:\Users\Admin\Desktop\django_project\env\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\Admin\Desktop\django_project\env\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Admin\Desktop\django_project\env\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Admin\Desktop\django_project\env\lib\site-packages\django\views\generic\base.py", line 101, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\Admin\Desktop\django_project\test_project\students\views.py", line 31, in get
    f = open('logs/debug3.logs', 'r')
FileNotFoundError: [Errno 2] No such file or directory: 'logs/debug3.logs'
ERROR2023-01-10 12:22:21,781 basehttp 12088  14984 "GET /logs/ HTTP/1.1" 500 72629
INFO2023-01-10 12:25:27,187 autoreload 12088  11092 C:\Users\Admin\Desktop\django_project\test_project\students\views.py changed, reloading.
INFO2023-01-10 12:25:28,258 autoreload 4964  9076 Watching for file changes with StatReloader
INFO2023-01-10 12:25:43,187 autoreload 4964  9076 C:\Users\Admin\Desktop\django_project\test_project\students\views.py changed, reloading.
INFO2023-01-10 12:25:44,631 autoreload 4576  2004 Watching for file changes with StatReloader
ERROR2023-01-10 12:26:04,972 log 4576  4892 Internal Server Error: /logs/
Traceback (most recent call last):
  File "C:\Users\Admin\Desktop\django_project\env\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\Admin\Desktop\django_project\env\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Admin\Desktop\django_project\env\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Admin\Desktop\django_project\env\lib\site-packages\django\views\generic\base.py", line 101, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\Admin\Desktop\django_project\test_project\students\views.py", line 31, in get
    filepath = open(os.path.join(settings.BASE_DIR, 'debug3.logs'))
NameError: name 'settings' is not defined
ERROR2023-01-10 12:26:04,975 basehttp 4576  4892 "GET /logs/ HTTP/1.1" 500 72558
INFO2023-01-10 12:26:29,624 autoreload 4576  2004 C:\Users\Admin\Desktop\django_project\test_project\students\views.py changed, reloading.
INFO2023-01-10 12:26:30,621 autoreload 5196  9908 Watching for file changes with StatReloader
INFO2023-01-10 12:27:51,200 autoreload 5196  9908 C:\Users\Admin\Desktop\django_project\test_project\students\views.py changed, reloading.
INFO2023-01-10 12:27:52,283 autoreload 11084  10784 Watching for file changes with StatReloader
ERROR2023-01-10 12:27:59,827 log 11084  13868 Internal Server Error: /logs/
Traceback (most recent call last):
  File "C:\Users\Admin\Desktop\django_project\env\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\Admin\Desktop\django_project\env\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Admin\Desktop\django_project\env\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Admin\Desktop\django_project\env\lib\site-packages\django\views\generic\base.py", line 101, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\Admin\Desktop\django_project\test_project\students\views.py", line 32, in get
    filepath = open(os.path.join(settings.BASE_DIR, 'debug3.logs'))
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Admin\\Desktop\\django_project\\test_project\\debug3.logs'
ERROR2023-01-10 12:27:59,832 basehttp 11084  13868 "GET /logs/ HTTP/1.1" 500 72825
INFO2023-01-10 12:28:34,309 autoreload 11084  10784 C:\Users\Admin\Desktop\django_project\test_project\students\views.py changed, reloading.
INFO2023-01-10 12:28:35,479 autoreload 11972  2636 Watching for file changes with StatReloader
ERROR2023-01-10 12:28:37,496 log 11972  4552 Internal Server Error: /logs/
Traceback (most recent call last):
  File "C:\Users\Admin\Desktop\django_project\env\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\Admin\Desktop\django_project\env\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Admin\Desktop\django_project\env\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Admin\Desktop\django_project\env\lib\site-packages\django\views\generic\base.py", line 101, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\Admin\Desktop\django_project\test_project\students\views.py", line 32, in get
    filepath = open(os.path.join(settings.BASE_DIR, '/logs/debug3.logs'))
FileNotFoundError: [Errno 2] No such file or directory: 'C:/logs/debug3.logs'
ERROR2023-01-10 12:28:37,498 basehttp 11972  4552 "GET /logs/ HTTP/1.1" 500 72690
INFO2023-01-10 12:36:12,717 autoreload 11972  2636 C:\Users\Admin\Desktop\django_project\test_project\students\views.py changed, reloading.
INFO2023-01-10 12:36:13,789 autoreload 12260  13048 Watching for file changes with StatReloader
ERROR2023-01-10 12:39:46,663 log 12260  7520 Internal Server Error: /logs/
Traceback (most recent call last):
  File "C:\Users\Admin\Desktop\django_project\env\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\Admin\Desktop\django_project\env\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Admin\Desktop\django_project\env\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Admin\Desktop\django_project\env\lib\site-packages\django\views\generic\base.py", line 101, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\Admin\Desktop\django_project\test_project\students\views.py", line 32, in get
    filepath = open(os.path.join(settings.BASE_DIR, 'debug3.logs'))
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Admin\\Desktop\\django_project\\test_project\\debug3.logs'
ERROR2023-01-10 12:39:46,666 basehttp 12260  7520 "GET /logs/ HTTP/1.1" 500 72825
INFO2023-01-10 12:45:02,271 autoreload 12260  13048 C:\Users\Admin\Desktop\django_project\test_project\students\views.py changed, reloading.
INFO2023-01-10 12:45:03,310 autoreload 2788  16644 Watching for file changes with StatReloader
INFO2023-01-10 12:45:10,691 autoreload 2788  16644 C:\Users\Admin\Desktop\django_project\test_project\students\views.py changed, reloading.
INFO2023-01-10 12:45:11,730 autoreload 8800  2588 Watching for file changes with StatReloader
INFO2023-01-10 12:45:28,758 autoreload 8800  2588 C:\Users\Admin\Desktop\django_project\test_project\students\views.py changed, reloading.
INFO2023-01-10 12:45:30,034 autoreload 5700  17236 Watching for file changes with StatReloader
INFO2023-01-10 12:46:08,211 autoreload 5700  17236 C:\Users\Admin\Desktop\django_project\test_project\students\views.py changed, reloading.
INFO2023-01-10 12:46:09,378 autoreload 17348  6024 Watching for file changes with StatReloader
ERROR2023-01-10 12:46:13,103 log 17348  15708 Internal Server Error: /logs/
Traceback (most recent call last):
  File "C:\Users\Admin\Desktop\django_project\env\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\Admin\Desktop\django_project\env\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Admin\Desktop\django_project\env\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Admin\Desktop\django_project\env\lib\site-packages\django\views\generic\base.py", line 101, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\Admin\Desktop\django_project\test_project\students\views.py", line 32, in get
    filepath = open(os.path.join(settings.BASE_DIR, 'logs\debug3.logs'))
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Admin\\Desktop\\django_project\\test_project\\logs\\debug3.logs'
ERROR2023-01-10 12:46:13,105 basehttp 17348  15708 "GET /logs/ HTTP/1.1" 500 72853
INFO2023-01-10 12:46:27,976 autoreload 17348  6024 C:\Users\Admin\Desktop\django_project\test_project\students\views.py changed, reloading.
INFO2023-01-10 12:46:29,144 autoreload 17016  12080 Watching for file changes with StatReloader
INFO2023-01-10 12:46:36,354 autoreload 17016  12080 C:\Users\Admin\Desktop\django_project\test_project\students\views.py changed, reloading.
INFO2023-01-10 12:46:37,474 autoreload 8920  1848 Watching for file changes with StatReloader
ERROR2023-01-10 12:46:39,045 log 8920  17240 Internal Server Error: /logs/
Traceback (most recent call last):
  File "C:\Users\Admin\Desktop\django_project\env\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\Admin\Desktop\django_project\env\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Admin\Desktop\django_project\env\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Admin\Desktop\django_project\env\lib\site-packages\django\views\generic\base.py", line 101, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\Admin\Desktop\django_project\test_project\students\views.py", line 32, in get
    filepath = open(os.path.join(settings.BASE_DIR, 'logs\\debug3.logs'))
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Admin\\Desktop\\django_project\\test_project\\logs\\debug3.logs'
ERROR2023-01-10 12:46:39,048 basehttp 8920  17240 "GET /logs/ HTTP/1.1" 500 72855
INFO2023-01-10 12:47:27,740 autoreload 8920  1848 C:\Users\Admin\Desktop\django_project\test_project\students\views.py changed, reloading.
INFO2023-01-10 12:47:28,775 autoreload 2244  14020 Watching for file changes with StatReloader
ERROR2023-01-10 12:47:31,992 log 2244  4980 Internal Server Error: /logs/
Traceback (most recent call last):
  File "C:\Users\Admin\Desktop\django_project\env\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\Admin\Desktop\django_project\env\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Admin\Desktop\django_project\env\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Admin\Desktop\django_project\env\lib\site-packages\django\views\generic\base.py", line 101, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\Admin\Desktop\django_project\test_project\students\views.py", line 32, in get
    filepath = open(os.path.join(settings.BASE_DIR, 'debug3.logs'))
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Admin\\Desktop\\django_project\\test_project\\debug3.logs'
ERROR2023-01-10 12:47:31,996 basehttp 2244  4980 "GET /logs/ HTTP/1.1" 500 72879
INFO2023-01-10 12:48:27,485 autoreload 2244  14020 C:\Users\Admin\Desktop\django_project\test_project\students\views.py changed, reloading.
INFO2023-01-10 12:48:28,513 autoreload 15040  2068 Watching for file changes with StatReloader
ERROR2023-01-10 12:48:32,739 log 15040  10556 Internal Server Error: /logs/
Traceback (most recent call last):
  File "C:\Users\Admin\Desktop\django_project\env\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\Admin\Desktop\django_project\env\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Admin\Desktop\django_project\env\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Admin\Desktop\django_project\env\lib\site-packages\django\views\generic\base.py", line 101, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\Admin\Desktop\django_project\test_project\students\views.py", line 32, in get
    context = super().get_context_data(request)
AttributeError: 'super' object has no attribute 'get_context_data'
ERROR2023-01-10 12:48:32,742 basehttp 15040  10556 "GET /logs/ HTTP/1.1" 500 72909
INFO2023-01-10 12:50:48,801 autoreload 15040  2068 C:\Users\Admin\Desktop\django_project\test_project\students\views.py changed, reloading.
INFO2023-01-10 12:50:50,236 autoreload 16212  3740 Watching for file changes with StatReloader
WARNING2023-01-10 12:50:59,424 base 16212  9660 Method Not Allowed (GET): /logs/
WARNING2023-01-10 12:50:59,428 log 16212  9660 Method Not Allowed: /logs/
WARNING2023-01-10 12:50:59,429 basehttp 16212  9660 "GET /logs/ HTTP/1.1" 405 0
INFO2023-01-10 12:51:39,906 autoreload 16212  3740 C:\Users\Admin\Desktop\django_project\test_project\students\views.py changed, reloading.
INFO2023-01-10 12:51:41,049 autoreload 14096  7040 Watching for file changes with StatReloader
INFO2023-01-10 12:51:47,465 autoreload 14096  7040 C:\Users\Admin\Desktop\django_project\test_project\students\views.py changed, reloading.
INFO2023-01-10 12:51:48,597 autoreload 11760  15256 Watching for file changes with StatReloader
WARNING2023-01-10 12:51:51,189 base 11760  1524 Method Not Allowed (GET): /logs/
WARNING2023-01-10 12:51:51,190 log 11760  1524 Method Not Allowed: /logs/
WARNING2023-01-10 12:51:51,191 basehttp 11760  1524 "GET /logs/ HTTP/1.1" 405 0
INFO2023-01-10 12:52:28,174 autoreload 11760  15256 C:\Users\Admin\Desktop\django_project\test_project\students\views.py changed, reloading.
INFO2023-01-10 12:52:29,220 autoreload 9748  11268 Watching for file changes with StatReloader
INFO2023-01-10 12:52:31,136 autoreload 9748  11268 C:\Users\Admin\Desktop\django_project\test_project\students\views.py changed, reloading.
INFO2023-01-10 12:52:32,273 autoreload 4400  2188 Watching for file changes with StatReloader
WARNING2023-01-10 12:52:33,316 base 4400  8124 Method Not Allowed (GET): /logs/
WARNING2023-01-10 12:52:33,318 log 4400  8124 Method Not Allowed: /logs/
WARNING2023-01-10 12:52:33,319 basehttp 4400  8124 "GET /logs/ HTTP/1.1" 405 0
INFO2023-01-10 13:13:51,499 autoreload 4400  2188 C:\Users\Admin\Desktop\django_project\test_project\students\views.py changed, reloading.
INFO2023-01-10 13:13:52,805 autoreload 15536  5604 Watching for file changes with StatReloader
INFO2023-01-10 13:13:54,563 autoreload 15536  5604 C:\Users\Admin\Desktop\django_project\test_project\students\views.py changed, reloading.
INFO2023-01-10 13:13:55,549 autoreload 4316  7140 Watching for file changes with StatReloader
INFO2023-01-10 13:15:08,942 autoreload 4316  7140 C:\Users\Admin\Desktop\django_project\test_project\students\views.py changed, reloading.
INFO2023-01-10 13:15:10,079 autoreload 14668  6492 Watching for file changes with StatReloader
INFO2023-01-10 13:15:15,078 autoreload 14668  6492 C:\Users\Admin\Desktop\django_project\test_project\students\views.py changed, reloading.
INFO2023-01-10 13:15:16,224 autoreload 6696  8256 Watching for file changes with StatReloader
WARNING2023-01-10 13:15:20,001 base 6696  13608 Method Not Allowed (GET): /logs/
WARNING2023-01-10 13:15:20,002 log 6696  13608 Method Not Allowed: /logs/
WARNING2023-01-10 13:15:20,003 basehttp 6696  13608 "GET /logs/ HTTP/1.1" 405 0
INFO2023-01-10 13:15:31,776 autoreload 6696  8256 C:\Users\Admin\Desktop\django_project\test_project\students\views.py changed, reloading.
INFO2023-01-10 13:15:32,851 autoreload 3584  2108 Watching for file changes with StatReloader
INFO2023-01-10 13:15:36,831 autoreload 3584  2108 C:\Users\Admin\Desktop\django_project\test_project\students\views.py changed, reloading.
INFO2023-01-10 13:15:37,910 autoreload 7132  15684 Watching for file changes with StatReloader
WARNING2023-01-10 13:15:40,280 base 7132  5220 Method Not Allowed (GET): /logs/
WARNING2023-01-10 13:15:40,283 log 7132  5220 Method Not Allowed: /logs/
WARNING2023-01-10 13:15:40,285 basehttp 7132  5220 "GET /logs/ HTTP/1.1" 405 0
INFO2023-01-10 13:16:05,133 autoreload 7132  15684 C:\Users\Admin\Desktop\django_project\test_project\students\views.py changed, reloading.
INFO2023-01-10 13:16:06,239 autoreload 9096  12264 Watching for file changes with StatReloader
INFO2023-01-10 13:16:21,394 autoreload 9096  12264 C:\Users\Admin\Desktop\django_project\test_project\students\views.py changed, reloading.
INFO2023-01-10 13:16:23,060 autoreload 11088  1968 Watching for file changes with StatReloader
INFO2023-01-10 13:16:26,080 autoreload 11088  1968 C:\Users\Admin\Desktop\django_project\test_project\students\views.py changed, reloading.
INFO2023-01-10 13:16:27,105 autoreload 14104  12992 Watching for file changes with StatReloader
WARNING2023-01-10 13:16:29,727 base 14104  12844 Method Not Allowed (GET): /logs/
WARNING2023-01-10 13:16:29,728 log 14104  12844 Method Not Allowed: /logs/
WARNING2023-01-10 13:16:29,728 basehttp 14104  12844 "GET /logs/ HTTP/1.1" 405 0
INFO2023-01-10 13:16:40,605 autoreload 14104  12992 C:\Users\Admin\Desktop\django_project\test_project\students\views.py changed, reloading.
INFO2023-01-10 13:16:41,823 autoreload 13716  13256 Watching for file changes with StatReloader
INFO2023-01-10 13:16:43,079 basehttp 13716  11704 "GET /logs/ HTTP/1.1" 200 85
INFO2023-01-10 13:17:14,306 autoreload 13716  13256 C:\Users\Admin\Desktop\django_project\test_project\students\views.py changed, reloading.
INFO2023-01-10 13:17:15,940 autoreload 17160  10688 Watching for file changes with StatReloader
INFO2023-01-10 13:17:16,449 basehttp 17160  7828 "GET /logs/ HTTP/1.1" 200 85
INFO2023-01-10 13:20:05,190 autoreload 17160  10688 C:\Users\Admin\Desktop\django_project\test_project\students\views.py changed, reloading.
INFO2023-01-10 13:20:06,299 autoreload 8304  16432 Watching for file changes with StatReloader
WARNING2023-01-10 13:20:11,059 base 8304  8332 Method Not Allowed (GET): /logs/
WARNING2023-01-10 13:20:11,060 log 8304  8332 Method Not Allowed: /logs/
WARNING2023-01-10 13:20:11,061 basehttp 8304  8332 "GET /logs/ HTTP/1.1" 405 0
INFO2023-01-10 13:20:42,532 autoreload 8304  16432 C:\Users\Admin\Desktop\django_project\test_project\students\views.py changed, reloading.
INFO2023-01-10 13:20:43,518 autoreload 13252  6004 Watching for file changes with StatReloader
INFO2023-01-10 13:21:26,823 autoreload 13252  6004 C:\Users\Admin\Desktop\django_project\test_project\students\views.py changed, reloading.
INFO2023-01-10 13:21:27,877 autoreload 10784  15696 Watching for file changes with StatReloader
INFO2023-01-10 13:21:39,173 autoreload 10784  15696 C:\Users\Admin\Desktop\django_project\test_project\students\views.py changed, reloading.
INFO2023-01-10 13:21:40,111 autoreload 16760  15932 Watching for file changes with StatReloader
INFO2023-01-10 13:23:10,288 autoreload 16760  15932 C:\Users\Admin\Desktop\django_project\test_project\students\views.py changed, reloading.
INFO2023-01-10 13:23:11,379 autoreload 12168  12184 Watching for file changes with StatReloader
WARNING2023-01-10 13:23:13,695 base 12168  1556 Method Not Allowed (GET): /logs/
WARNING2023-01-10 13:23:13,696 log 12168  1556 Method Not Allowed: /logs/
WARNING2023-01-10 13:23:13,698 basehttp 12168  1556 "GET /logs/ HTTP/1.1" 405 0
INFO2023-01-10 13:23:49,741 autoreload 12168  12184 C:\Users\Admin\Desktop\django_project\test_project\students\views.py changed, reloading.
INFO2023-01-10 13:23:50,852 autoreload 8360  7040 Watching for file changes with StatReloader
INFO2023-01-10 13:23:53,736 autoreload 8360  7040 C:\Users\Admin\Desktop\django_project\test_project\students\views.py changed, reloading.
INFO2023-01-10 13:23:54,709 autoreload 14080  11464 Watching for file changes with StatReloader
INFO2023-01-10 13:24:21,027 autoreload 14080  11464 C:\Users\Admin\Desktop\django_project\test_project\students\views.py changed, reloading.
INFO2023-01-10 13:24:21,979 autoreload 13060  15128 Watching for file changes with StatReloader
INFO2023-01-10 13:24:57,926 autoreload 13060  15128 C:\Users\Admin\Desktop\django_project\test_project\students\views.py changed, reloading.
INFO2023-01-10 13:24:58,841 autoreload 15612  14152 Watching for file changes with StatReloader
INFO2023-01-10 13:38:17,023 autoreload 15612  14152 C:\Users\Admin\Desktop\django_project\test_project\students\views.py changed, reloading.
INFO2023-01-10 13:38:18,008 autoreload 14388  13016 Watching for file changes with StatReloader
INFO2023-01-10 13:38:30,433 autoreload 14388  13016 C:\Users\Admin\Desktop\django_project\test_project\students\views.py changed, reloading.
INFO2023-01-10 13:38:31,501 autoreload 13848  4756 Watching for file changes with StatReloader
WARNING2023-01-10 13:38:33,022 base 13848  14752 Method Not Allowed (GET): /logs/
WARNING2023-01-10 13:38:33,023 log 13848  14752 Method Not Allowed: /logs/
WARNING2023-01-10 13:38:33,024 basehttp 13848  14752 "GET /logs/ HTTP/1.1" 405 0
WARNING2023-01-10 13:38:34,614 base 13848  14752 Method Not Allowed (GET): /logs/
WARNING2023-01-10 13:38:34,614 log 13848  14752 Method Not Allowed: /logs/
WARNING2023-01-10 13:38:34,615 basehttp 13848  14752 "GET /logs/ HTTP/1.1" 405 0
WARNING2023-01-10 13:38:34,859 base 13848  14752 Method Not Allowed (GET): /logs/
WARNING2023-01-10 13:38:34,860 log 13848  14752 Method Not Allowed: /logs/
WARNING2023-01-10 13:38:34,860 basehttp 13848  14752 "GET /logs/ HTTP/1.1" 405 0
WARNING2023-01-10 13:38:35,035 base 13848  14752 Method Not Allowed (GET): /logs/
WARNING2023-01-10 13:38:35,036 log 13848  14752 Method Not Allowed: /logs/
WARNING2023-01-10 13:38:35,036 basehttp 13848  14752 "GET /logs/ HTTP/1.1" 405 0
INFO2023-01-10 13:38:41,983 autoreload 12928  15124 Watching for file changes with StatReloader
WARNING2023-01-10 13:38:44,968 base 12928  8728 Method Not Allowed (GET): /logs/
WARNING2023-01-10 13:38:44,969 log 12928  8728 Method Not Allowed: /logs/
WARNING2023-01-10 13:38:44,970 basehttp 12928  8728 "GET /logs/ HTTP/1.1" 405 0
WARNING2023-01-10 13:38:45,643 base 12928  8728 Method Not Allowed (GET): /logs/
WARNING2023-01-10 13:38:45,644 log 12928  8728 Method Not Allowed: /logs/
WARNING2023-01-10 13:38:45,645 basehttp 12928  8728 "GET /logs/ HTTP/1.1" 405 0
INFO2023-01-10 13:39:12,901 autoreload 12928  15124 C:\Users\Admin\Desktop\django_project\test_project\students\views.py changed, reloading.
INFO2023-01-10 13:39:13,859 autoreload 17072  6840 Watching for file changes with StatReloader
WARNING2023-01-10 13:39:16,601 base 17072  9332 Method Not Allowed (GET): /logs/
WARNING2023-01-10 13:39:16,602 log 17072  9332 Method Not Allowed: /logs/
WARNING2023-01-10 13:39:16,603 basehttp 17072  9332 "GET /logs/ HTTP/1.1" 405 0
INFO2023-01-10 13:39:41,557 autoreload 17072  6840 C:\Users\Admin\Desktop\django_project\test_project\students\views.py changed, reloading.
INFO2023-01-10 13:39:42,529 autoreload 1080  16916 Watching for file changes with StatReloader
WARNING2023-01-10 13:39:45,534 base 1080  9372 Method Not Allowed (GET): /logs/
WARNING2023-01-10 13:39:45,536 log 1080  9372 Method Not Allowed: /logs/
WARNING2023-01-10 13:39:45,536 basehttp 1080  9372 "GET /logs/ HTTP/1.1" 405 0
INFO2023-01-10 13:39:58,282 autoreload 1080  16916 C:\Users\Admin\Desktop\django_project\test_project\students\views.py changed, reloading.
INFO2023-01-10 13:39:59,421 autoreload 15772  13456 Watching for file changes with StatReloader
WARNING2023-01-10 13:40:00,328 base 15772  3536 Method Not Allowed (GET): /logs/
WARNING2023-01-10 13:40:00,328 log 15772  3536 Method Not Allowed: /logs/
WARNING2023-01-10 13:40:00,329 basehttp 15772  3536 "GET /logs/ HTTP/1.1" 405 0
INFO2023-01-10 13:45:00,102 autoreload 15772  13456 C:\Users\Admin\Desktop\django_project\test_project\students\views.py changed, reloading.
INFO2023-01-10 13:45:01,060 autoreload 16632  16044 Watching for file changes with StatReloader
WARNING2023-01-10 13:45:03,710 base 16632  11196 Method Not Allowed (GET): /logs/
WARNING2023-01-10 13:45:03,712 log 16632  11196 Method Not Allowed: /logs/
WARNING2023-01-10 13:45:03,713 basehttp 16632  11196 "GET /logs/ HTTP/1.1" 405 0
INFO2023-01-10 13:45:12,797 autoreload 16632  16044 C:\Users\Admin\Desktop\django_project\test_project\students\views.py changed, reloading.
INFO2023-01-10 13:45:13,759 autoreload 10592  14068 Watching for file changes with StatReloader
ERROR2023-01-10 13:45:16,956 log 10592  68 Internal Server Error: /logs/
Traceback (most recent call last):
  File "C:\Users\Admin\Desktop\django_project\env\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\Admin\Desktop\django_project\env\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Admin\Desktop\django_project\env\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Admin\Desktop\django_project\env\lib\site-packages\django\views\generic\base.py", line 101, in dispatch
    return handler(request, *args, **kwargs)
TypeError: Logs.get() takes 1 positional argument but 2 were given
ERROR2023-01-10 13:45:16,959 basehttp 10592  68 "GET /logs/ HTTP/1.1" 500 68783
INFO2023-01-10 13:45:31,600 autoreload 10592  14068 C:\Users\Admin\Desktop\django_project\test_project\students\views.py changed, reloading.
INFO2023-01-10 13:45:32,613 autoreload 14808  13392 Watching for file changes with StatReloader
ERROR2023-01-10 13:45:34,013 log 14808  14928 Internal Server Error: /logs/
Traceback (most recent call last):
  File "C:\Users\Admin\Desktop\django_project\env\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\Admin\Desktop\django_project\env\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Admin\Desktop\django_project\env\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Admin\Desktop\django_project\env\lib\site-packages\django\views\generic\base.py", line 101, in dispatch
    return handler(request, *args, **kwargs)
TypeError: Logs.get() takes 1 positional argument but 2 were given
ERROR2023-01-10 13:45:34,014 basehttp 14808  14928 "GET /logs/ HTTP/1.1" 500 68783
INFO2023-01-10 13:45:47,123 autoreload 14808  13392 C:\Users\Admin\Desktop\django_project\test_project\students\views.py changed, reloading.
INFO2023-01-10 13:45:48,074 autoreload 896  14280 Watching for file changes with StatReloader
INFO2023-01-10 13:45:50,205 basehttp 896  16180 "GET /logs/ HTTP/1.1" 200 85
INFO2023-01-10 13:50:03,788 autoreload 896  14280 C:\Users\Admin\Desktop\django_project\test_project\students\views.py changed, reloading.
INFO2023-01-10 13:50:04,820 autoreload 15684  10852 Watching for file changes with StatReloader
INFO2023-01-10 13:50:31,235 autoreload 15684  10852 C:\Users\Admin\Desktop\django_project\test_project\students\views.py changed, reloading.
INFO2023-01-10 13:50:32,200 autoreload 4052  11816 Watching for file changes with StatReloader
INFO2023-01-10 13:50:45,709 autoreload 4052  11816 C:\Users\Admin\Desktop\django_project\test_project\students\views.py changed, reloading.
INFO2023-01-10 13:50:46,641 autoreload 5044  16444 Watching for file changes with StatReloader
ERROR2023-01-10 13:50:49,844 log 5044  3536 Internal Server Error: /logs/
Traceback (most recent call last):
  File "C:\Users\Admin\Desktop\django_project\env\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\Admin\Desktop\django_project\env\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Admin\Desktop\django_project\env\lib\site-packages\django\views\generic\base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Admin\Desktop\django_project\env\lib\site-packages\django\views\generic\base.py", line 101, in dispatch
    return handler(request, *args, **kwargs)
TypeError: Logs.get() takes 1 positional argument but 2 were given
ERROR2023-01-10 13:50:49,846 basehttp 5044  3536 "GET /logs/ HTTP/1.1" 500 68783
INFO2023-01-10 13:51:08,760 autoreload 5044  16444 C:\Users\Admin\Desktop\django_project\test_project\students\views.py changed, reloading.
INFO2023-01-10 13:51:09,723 autoreload 4872  12412 Watching for file changes with StatReloader
WARNING2023-01-10 13:51:14,126 base 4872  5460 Method Not Allowed (GET): /logs/
WARNING2023-01-10 13:51:14,127 log 4872  5460 Method Not Allowed: /logs/
WARNING2023-01-10 13:51:14,128 basehttp 4872  5460 "GET /logs/ HTTP/1.1" 405 0
INFO2023-01-10 13:55:00,021 autoreload 4872  12412 C:\Users\Admin\Desktop\django_project\test_project\students\views.py changed, reloading.
INFO2023-01-10 13:55:00,964 autoreload 8356  14344 Watching for file changes with StatReloader
INFO2023-01-10 16:15:31,572 autoreload 8356  14344 C:\Users\Admin\Desktop\django_project\test_project\students\views.py changed, reloading.
INFO2023-01-10 16:15:32,533 autoreload 14252  7276 Watching for file changes with StatReloader
INFO2023-01-10 16:15:54,409 autoreload 14252  7276 C:\Users\Admin\Desktop\django_project\test_project\students\views.py changed, reloading.
INFO2023-01-10 16:15:55,301 autoreload 1056  11464 Watching for file changes with StatReloader
WARNING2023-01-10 16:16:03,444 base 1056  4052 Method Not Allowed (GET): /logs/
WARNING2023-01-10 16:16:03,445 log 1056  4052 Method Not Allowed: /logs/
WARNING2023-01-10 16:16:03,445 basehttp 1056  4052 "GET /logs/ HTTP/1.1" 405 0
WARNING2023-01-10 16:16:04,287 base 1056  4052 Method Not Allowed (GET): /logs/
WARNING2023-01-10 16:16:04,287 log 1056  4052 Method Not Allowed: /logs/
WARNING2023-01-10 16:16:04,289 basehttp 1056  4052 "GET /logs/ HTTP/1.1" 405 0
INFO2023-01-10 16:22:37,458 autoreload 1056  11464 C:\Users\Admin\Desktop\django_project\test_project\students\urls.py changed, reloading.
INFO2023-01-10 16:22:38,534 autoreload 14092  11488 Watching for file changes with StatReloader
INFO2023-01-10 16:45:30,856 autoreload 14092  11488 C:\Users\Admin\Desktop\django_project\test_project\students\views.py changed, reloading.
INFO2023-01-10 16:45:31,797 autoreload 16308  13560 Watching for file changes with StatReloader
INFO2023-01-10 16:45:59,836 autoreload 16308  13560 C:\Users\Admin\Desktop\django_project\test_project\students\views.py changed, reloading.
INFO2023-01-10 16:46:00,809 autoreload 8332  1192 Watching for file changes with StatReloader
INFO2023-01-10 16:46:45,443 autoreload 8332  1192 C:\Users\Admin\Desktop\django_project\test_project\students\views.py changed, reloading.
INFO2023-01-10 16:46:46,430 autoreload 12124  12172 Watching for file changes with StatReloader
INFO2023-01-10 16:54:39,780 autoreload 12124  12172 C:\Users\Admin\Desktop\django_project\test_project\students\views.py changed, reloading.
INFO2023-01-10 16:54:40,705 autoreload 2572  5544 Watching for file changes with StatReloader
INFO2023-01-10 16:54:46,642 autoreload 2572  5544 C:\Users\Admin\Desktop\django_project\test_project\students\views.py changed, reloading.
INFO2023-01-10 16:54:47,512 autoreload 15948  14536 Watching for file changes with StatReloader
WARNING2023-01-10 16:55:36,166 base 15948  14756 Method Not Allowed (GET): /logs/
WARNING2023-01-10 16:55:36,167 log 15948  14756 Method Not Allowed: /logs/
WARNING2023-01-10 16:55:36,168 basehttp 15948  14756 "GET /logs/ HTTP/1.1" 405 0
WARNING2023-01-10 16:55:37,523 base 15948  14756 Method Not Allowed (GET): /logs/
WARNING2023-01-10 16:55:37,525 log 15948  14756 Method Not Allowed: /logs/
WARNING2023-01-10 16:55:37,526 basehttp 15948  14756 "GET /logs/ HTTP/1.1" 405 0
WARNING2023-01-10 16:55:37,952 base 15948  14756 Method Not Allowed (GET): /logs/
WARNING2023-01-10 16:55:37,952 log 15948  14756 Method Not Allowed: /logs/
WARNING2023-01-10 16:55:37,953 basehttp 15948  14756 "GET /logs/ HTTP/1.1" 405 0
WARNING2023-01-10 16:55:38,154 base 15948  14756 Method Not Allowed (GET): /logs/
WARNING2023-01-10 16:55:38,154 log 15948  14756 Method Not Allowed: /logs/
WARNING2023-01-10 16:55:38,155 basehttp 15948  14756 "GET /logs/ HTTP/1.1" 405 0
INFO2023-01-10 16:55:48,619 autoreload 876  16728 Watching for file changes with StatReloader
WARNING2023-01-10 16:55:51,930 base 876  12032 Method Not Allowed (GET): /logs/
WARNING2023-01-10 16:55:51,931 log 876  12032 Method Not Allowed: /logs/
WARNING2023-01-10 16:55:51,931 basehttp 876  12032 "GET /logs/ HTTP/1.1" 405 0
WARNING2023-01-10 16:55:52,078 base 876  12032 Method Not Allowed (GET): /logs/
WARNING2023-01-10 16:55:52,078 log 876  12032 Method Not Allowed: /logs/
WARNING2023-01-10 16:55:52,079 basehttp 876  12032 "GET /logs/ HTTP/1.1" 405 0
WARNING2023-01-10 16:55:52,272 base 876  12032 Method Not Allowed (GET): /logs/
WARNING2023-01-10 16:55:52,273 log 876  12032 Method Not Allowed: /logs/
WARNING2023-01-10 16:55:52,273 basehttp 876  12032 "GET /logs/ HTTP/1.1" 405 0
WARNING2023-01-10 16:55:52,458 base 876  12032 Method Not Allowed (GET): /logs/
WARNING2023-01-10 16:55:52,459 log 876  12032 Method Not Allowed: /logs/
WARNING2023-01-10 16:55:52,460 basehttp 876  12032 "GET /logs/ HTTP/1.1" 405 0
WARNING2023-01-10 16:55:52,640 base 876  12032 Method Not Allowed (GET): /logs/
WARNING2023-01-10 16:55:52,641 log 876  12032 Method Not Allowed: /logs/
WARNING2023-01-10 16:55:52,642 basehttp 876  12032 "GET /logs/ HTTP/1.1" 405 0
INFO2023-01-10 16:56:10,861 autoreload 876  16728 C:\Users\Admin\Desktop\django_project\test_project\students\views.py changed, reloading.
INFO2023-01-10 16:56:11,768 autoreload 9736  1060 Watching for file changes with StatReloader
WARNING2023-01-10 16:56:19,072 base 9736  1712 Method Not Allowed (GET): /logs/
WARNING2023-01-10 16:56:19,073 log 9736  1712 Method Not Allowed: /logs/
WARNING2023-01-10 16:56:19,074 basehttp 9736  1712 "GET /logs/ HTTP/1.1" 405 0
WARNING2023-01-10 16:56:19,680 base 9736  1712 Method Not Allowed (GET): /logs/
WARNING2023-01-10 16:56:19,681 log 9736  1712 Method Not Allowed: /logs/
WARNING2023-01-10 16:56:19,681 basehttp 9736  1712 "GET /logs/ HTTP/1.1" 405 0
WARNING2023-01-10 16:56:19,893 base 9736  1712 Method Not Allowed (GET): /logs/
WARNING2023-01-10 16:56:19,894 log 9736  1712 Method Not Allowed: /logs/
WARNING2023-01-10 16:56:19,895 basehttp 9736  1712 "GET /logs/ HTTP/1.1" 405 0
WARNING2023-01-10 16:56:20,109 base 9736  1712 Method Not Allowed (GET): /logs/
WARNING2023-01-10 16:56:20,110 log 9736  1712 Method Not Allowed: /logs/
WARNING2023-01-10 16:56:20,111 basehttp 9736  1712 "GET /logs/ HTTP/1.1" 405 0
WARNING2023-01-10 16:56:20,367 base 9736  1712 Method Not Allowed (GET): /logs/
WARNING2023-01-10 16:56:20,367 log 9736  1712 Method Not Allowed: /logs/
WARNING2023-01-10 16:56:20,369 basehttp 9736  1712 "GET /logs/ HTTP/1.1" 405 0
WARNING2023-01-10 16:56:20,594 base 9736  1712 Method Not Allowed (GET): /logs/
WARNING2023-01-10 16:56:20,595 log 9736  1712 Method Not Allowed: /logs/
WARNING2023-01-10 16:56:20,596 basehttp 9736  1712 "GET /logs/ HTTP/1.1" 405 0
WARNING2023-01-10 16:56:20,778 base 9736  1712 Method Not Allowed (GET): /logs/
WARNING2023-01-10 16:56:20,778 log 9736  1712 Method Not Allowed: /logs/
WARNING2023-01-10 16:56:20,779 basehttp 9736  1712 "GET /logs/ HTTP/1.1" 405 0
INFO2023-01-10 16:56:46,840 autoreload 9736  1060 C:\Users\Admin\Desktop\django_project\test_project\students\views.py changed, reloading.
INFO2023-01-10 16:56:47,746 autoreload 15012  10844 Watching for file changes with StatReloader
INFO2023-01-10 17:37:03,755 autoreload 15012  10844 C:\Users\Admin\Desktop\django_project\test_project\students\views.py changed, reloading.
INFO2023-01-10 17:37:05,072 autoreload 14160  8360 Watching for file changes with StatReloader
INFO2023-01-10 17:37:44,417 autoreload 14160  8360 C:\Users\Admin\Desktop\django_project\test_project\students\views.py changed, reloading.
INFO2023-01-10 17:37:45,410 autoreload 8692  12340 Watching for file changes with StatReloader
INFO2023-01-10 17:37:54,768 autoreload 8692  12340 C:\Users\Admin\Desktop\django_project\test_project\students\views.py changed, reloading.
INFO2023-01-10 17:37:56,067 autoreload 7480  5400 Watching for file changes with StatReloader
INFO2023-01-10 17:38:04,423 autoreload 7480  5400 C:\Users\Admin\Desktop\django_project\test_project\students\views.py changed, reloading.
INFO2023-01-10 17:38:05,468 autoreload 14460  2584 Watching for file changes with StatReloader
INFO2023-01-10 17:38:11,627 autoreload 14460  2584 C:\Users\Admin\Desktop\django_project\test_project\students\views.py changed, reloading.
INFO2023-01-10 17:38:12,950 autoreload 1920  744 Watching for file changes with StatReloader
INFO2023-01-10 17:40:21,743 autoreload 1920  744 C:\Users\Admin\Desktop\django_project\test_project\students\views.py changed, reloading.
INFO2023-01-10 17:40:22,777 autoreload 16128  16068 Watching for file changes with StatReloader
WARNING2023-01-10 17:40:27,090 base 16128  16560 Method Not Allowed (GET): /logs/
WARNING2023-01-10 17:40:27,091 log 16128  16560 Method Not Allowed: /logs/
WARNING2023-01-10 17:40:27,092 basehttp 16128  16560 "GET /logs/ HTTP/1.1" 405 0
WARNING2023-01-10 17:40:28,591 base 16128  16560 Method Not Allowed (GET): /logs/
WARNING2023-01-10 17:40:28,591 log 16128  16560 Method Not Allowed: /logs/
WARNING2023-01-10 17:40:28,592 basehttp 16128  16560 "GET /logs/ HTTP/1.1" 405 0
WARNING2023-01-10 17:40:28,907 base 16128  16560 Method Not Allowed (GET): /logs/
WARNING2023-01-10 17:40:28,908 log 16128  16560 Method Not Allowed: /logs/
WARNING2023-01-10 17:40:28,910 basehttp 16128  16560 "GET /logs/ HTTP/1.1" 405 0
WARNING2023-01-10 17:40:29,110 base 16128  16560 Method Not Allowed (GET): /logs/
WARNING2023-01-10 17:40:29,111 log 16128  16560 Method Not Allowed: /logs/
WARNING2023-01-10 17:40:29,112 basehttp 16128  16560 "GET /logs/ HTTP/1.1" 405 0
WARNING2023-01-10 17:40:29,378 base 16128  16560 Method Not Allowed (GET): /logs/
WARNING2023-01-10 17:40:29,378 log 16128  16560 Method Not Allowed: /logs/
WARNING2023-01-10 17:40:29,379 basehttp 16128  16560 "GET /logs/ HTTP/1.1" 405 0
WARNING2023-01-10 17:40:29,575 base 16128  16560 Method Not Allowed (GET): /logs/
WARNING2023-01-10 17:40:29,575 log 16128  16560 Method Not Allowed: /logs/
WARNING2023-01-10 17:40:29,576 basehttp 16128  16560 "GET /logs/ HTTP/1.1" 405 0
WARNING2023-01-10 17:51:17,272 base 16128  15152 Method Not Allowed (GET): /logs/
WARNING2023-01-10 17:51:17,273 log 16128  15152 Method Not Allowed: /logs/
WARNING2023-01-10 17:51:17,274 basehttp 16128  15152 "GET /logs/ HTTP/1.1" 405 0
WARNING2023-01-10 17:51:17,981 base 16128  15152 Method Not Allowed (GET): /logs/
WARNING2023-01-10 17:51:17,981 log 16128  15152 Method Not Allowed: /logs/
WARNING2023-01-10 17:51:17,983 basehttp 16128  15152 "GET /logs/ HTTP/1.1" 405 0
INFO2023-01-10 19:16:14,135 autoreload 16128  16068 C:\Users\Admin\Desktop\django_project\test_project\students\views.py changed, reloading.
INFO2023-01-10 19:16:15,226 autoreload 17164  4892 Watching for file changes with StatReloader
